# Generated by Django 3.2 on 2021-04-26 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_leader', models.IntegerField(default=3)),
                ('delay_all', models.IntegerField(default=2)),
                ('EMAIL_BACKEND', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=50)),
                ('EMAIL_HOST', models.CharField(default='smtp.gmail.com', max_length=30)),
                ('EMAIL_PORT', models.IntegerField(default=587)),
                ('EMAIL_HOST_USER', models.CharField(default='carnetdjango@gmail.com', max_length=50)),
                ('EMAIL_HOST_PASSWORD', models.CharField(default='ozebijqmlwhlahqw', max_length=100)),
                ('EMAIL_USE_TLS', models.BooleanField(default=True)),
                ('DEFAULT_FROM_EMAIL', models.CharField(default='carnetdjango@gmail.com', max_length=50)),
                ('EMAIL_HEADER', models.CharField(default='"FFT - Food For Thought" <fft@comarch.pl>', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(default=None, max_length=250, unique_for_date='planning_date')),
                ('description', models.TextField(verbose_name='opis wydarzenia')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('planning_date', models.DateTimeField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('publish', 'Opublikowano')], default='publish', max_length=15)),
                ('duration', models.IntegerField()),
                ('icon', models.FileField(default='icons/default.png', upload_to='icons/')),
                ('attachment', models.FileField(blank=True, upload_to='attachments/')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('want_to_listen', models.ManyToManyField(blank=True, default=None, related_name='want_to_listen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('planning_date',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(default=None, max_length=200, unique_for_date='created')),
                ('description', models.TextField(max_length=400, verbose_name='opis tematu')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.IntegerField(default='0')),
                ('lead_count', models.IntegerField(default='0')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='like', to=settings.AUTH_USER_MODEL)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('want_to_lead', models.ManyToManyField(blank=True, default=None, related_name='want_to_lead', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_lead', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subject')),
            ],
        ),
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_sent_leader', models.BooleanField(default=False)),
                ('if_sent_all', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.event')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.emailset')),
            ],
        ),
    ]
