# Generated by Django 3.1.7 on 2021-04-18 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(default=None, max_length=200, unique_for_date='created')),
                ('description', models.TextField(max_length=400, verbose_name='opis tematu')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.IntegerField(default='0')),
                ('lead_count', models.IntegerField(default='0')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='like', to=settings.AUTH_USER_MODEL)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('want_to_lead', models.ManyToManyField(blank=True, default=None, related_name='want_to_lead', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_lead', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(default=None, max_length=250, unique_for_date='planning_date')),
                ('description', models.TextField(verbose_name='opis wydarzenia')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('planning_date', models.DateTimeField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('publish', 'Opublikowano')], default='publish', max_length=15)),
                ('duration', models.IntegerField()),
                ('icon', models.FileField(default='icons/default.png', upload_to='icons/')),
                ('attachment', models.FileField(blank=True, upload_to='attachments/')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('planning_date',),
            },
        ),
    ]
