# Generated by Django 3.1.7 on 2021-03-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Szkic'), ('publish', 'Opublikowano')], default='draft', max_length=15),
        ),
    ]
