# Generated by Django 3.1.7 on 2021-03-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=None, max_length=250, unique_for_date='planning_date'),
        ),
    ]
